In [1]:
import pandas as pd

In [36]:
df_trscrpt = pd.read_csv('earnings_transcripts_sorted.csv')
df_trscrpt.head()

,event_id,symbol,date,content
0,10404,AAPL,2005-10-13 14:45:00,TRANSCRIPT SPONSOR :\nApple's Q4 2005 Conferen...
1,32947,COP,2005-10-30 17:00:00,Operator: Ladies and gentlemen and welcome to ...
2,32026,GLW,2005-10-31 17:00:00,Operator: Good morning everyone. Welcome to t...
3,33031,XOM,2005-10-31 17:00:00,Operator: I would like to turn the call over t...
4,33161,XEL,2005-10-31 17:00:00,Operator: Good morning. My name is Dennis and...

In [24]:
df_mrkt = pd.read_csv('marketdata_to_events.csv')
df_mrkt.head()

,Date,Close,High,Low,Open,Volume,relative_day,window,event_id,symbol,earnings_timestamp
0,2020-10-13,101.290054,101.856944,100.848076,101.309275,915500,-29,pre,0,A,2020-11-23 16:30:00
1,2020-10-14,100.944176,102.491103,100.809661,101.357330,906700,-28,pre,0,A,2020-11-23 16:30:00
2,2020-10-15,101.193993,101.578324,99.810404,100.021786,723000,-27,pre,0,A,2020-11-23 16:30:00
3,2020-10-16,102.519936,103.327032,101.568722,101.799317,1039400,-26,pre,0,A,2020-11-23 16:30:00
4,2020-10-19,101.357330,103.403890,101.117124,102.596794,636000,-25,pre,0,A,2020-11-23 16:30:00

In [37]:
df_trscrpt.shape, df_mrkt.shape

((29574, 4), (1116586, 11))

In [38]:
#split train, validation, and test sets
n_events = len(df_trscrpt)
train_end = int(n_events * 0.70)
val_end = int(n_events * 0.85)

train_events = df_trscrpt.iloc[:train_end].copy()
val_events = df_trscrpt.iloc[train_end:val_end].copy()
test_events = df_trscrpt.iloc[val_end:].copy()

train_market = df_mrkt[df_mrkt["event_id"].isin(train_events["event_id"])].copy()
val_market = df_mrkt[df_mrkt["event_id"].isin(val_events["event_id"])].copy()
test_market = df_mrkt[df_mrkt["event_id"].isin(test_events["event_id"])].copy()

print("Events:")
print(f"Train:      {len(train_events):,}")
print(f"Validation: {len(val_events):,}")
print(f"Test:       {len(test_events):,}")

print("\nDate ranges:")
print(
    f"Train:      {train_events['date'].min()} → "
    f"{train_events['date'].max()}"
)
print(
    f"Validation: {val_events['date'].min()} → "
    f"{val_events['date'].max()}"
)
print(
    f"Test:       {test_events['date'].min()} → "
    f"{test_events['date'].max()}"
)

print("\nMarket rows:")
print(f"Train:      {len(train_market):,}")
print(f"Validation: {len(val_market):,}")
print(f"Test:       {len(test_market):,}")

Events:
Train:      20,701
Validation: 4,436
Test:       4,437

Date ranges:
Train:      2005-10-13 14:45:00 → 2021-01-19 09:00:00
Validation: 2021-01-19 09:30:00 → 2023-02-24 09:00:00
Test:       2023-02-24 09:00:00 → 2025-05-15 16:30:00

Market rows:
Train:      781,696
Validation: 167,421
Test:       167,469

In [40]:
# save the split datasets to CSV files
train_events.to_csv('data/train_events.csv', index=False)
val_events.to_csv('data/val_events.csv', index=False)
test_events.to_csv('data/test_events.csv', index=False)
train_market.to_csv('data/train_market.csv', index=False)
val_market.to_csv('data/val_market.csv', index=False)
test_market.to_csv('data/test_market.csv', index=False)